language: go

env:
  NODE_VERSION="5.0.0"

go:
  - 1.6
  - 1.7
  - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g webpack typings tslint

script:
  - make dist
  - go test -v ./...
  - go vet ./...
  - cd app && tslint --project ./tslint.json
