language: go

env:
  NODE_VERSION="4.0.0"

go:
  - 1.6
  - 1.7
  - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g webpack typings

script:
  - make app-prod
  - make server
  - cd server && go test ./... -cover
