language: go

env:
  NODE_VERSION="8.11.2"

go:
  - 1.11
  - 1.12
  - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g webpack yarn tslint typescript

script:
  - make dist
  - cd server && go test -v ./...
  - cd server && go vet ./...
  - cd app && tslint --project ./tslint.json
